ERROR   2022-05-09 10:46:38,530  C:\work\Study\pytest-auto-api2\logs\error.log:weChatSendControl.py:108 {'errcode': 40007, 'errmsg': 'invalid media_id, hint: [1652064398288640688240964], from ip: 115.227.221.158, more info at https://open.work.weixin.qq.com/devtool/query?e=40007'}
ERROR   2022-05-09 10:55:48,425  C:\work\Study\pytest-auto-api2\logs\error.log:weChatSendControl.py:116 {'errcode': 40007, 'errmsg': 'invalid media_id, hint: [1652064948173452008032592], from ip: 115.227.221.158, more info at https://open.work.weixin.qq.com/devtool/query?e=40007'}
ERROR   2022-05-09 10:55:56,576  C:\work\Study\pytest-auto-api2\logs\error.log:weChatSendControl.py:104 {'errcode': 44001, 'errmsg': 'empty media data, hint: [1652064956132492918238845], from ip: 115.227.221.158, more info at https://open.work.weixin.qq.com/devtool/query?e=44001'}
ERROR   2022-05-09 10:56:20,666  C:\work\Study\pytest-auto-api2\logs\error.log:weChatSendControl.py:104 {'errcode': 44001, 'errmsg': 'empty media data, hint: [1652064980188810844369449], from ip: 115.227.221.158, more info at https://open.work.weixin.qq.com/devtool/query?e=44001'}
ERROR   2022-05-09 10:56:41,016  C:\work\Study\pytest-auto-api2\logs\error.log:weChatSendControl.py:105 {'errcode': 44001, 'errmsg': 'empty media data, hint: [1652065000593813707418193], from ip: 115.227.221.158, more info at https://open.work.weixin.qq.com/devtool/query?e=44001'}
ERROR   2022-05-09 10:57:21,670  C:\work\Study\pytest-auto-api2\logs\error.log:weChatSendControl.py:105 {'errcode': 44001, 'errmsg': 'empty media data, hint: [1652065041593810628239782], from ip: 115.227.221.158, more info at https://open.work.weixin.qq.com/devtool/query?e=44001'}
ERROR   2022-05-09 10:57:57,220  C:\work\Study\pytest-auto-api2\logs\error.log:weChatSendControl.py:105 {'errcode': 44001, 'errmsg': 'empty media data, hint: [1652065077557012715287726], from ip: 115.227.221.158, more info at https://open.work.weixin.qq.com/devtool/query?e=44001'}
ERROR   2022-05-09 13:45:07,535  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 13:45:07,536  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-09 21:28:19,389  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 21:28:19,391  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-09 21:29:28,527  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 21:29:28,528  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-09 21:32:19,727  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 21:32:19,729  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-09 21:34:09,139  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 21:34:09,139  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-09 21:48:04,028  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 21:48:04,032  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-09 21:49:46,140  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 21:49:46,142  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-09 21:57:42,248  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 21:57:42,249  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-09 21:58:30,153  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 21:58:30,153  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-09 22:01:17,860  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-09 22:01:17,860  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-10 18:58:56,110  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-10 18:58:56,112  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-10 19:00:06,813  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-10 19:00:06,813  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-10 20:51:59,689  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-10 20:51:59,690  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-10 21:40:11,228  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-10 21:40:11,229  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-10 21:45:30,958  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-10 21:45:30,960  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-10 21:52:35,733  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-10 21:52:35,734  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-10 21:57:31,840  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-10 21:57:31,841  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-10 22:23:44,387  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-10 22:23:44,387  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-11 12:18:41,197  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-11 12:18:41,198  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-11 12:37:42,785  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-11 12:37:42,786  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-11 12:43:27,541  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-11 12:43:27,542  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-11 12:44:29,684  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-11 12:44:29,684  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-11 18:23:23,807  C:\work\Study\pytest-auto-api2\logs\error.log:assertControl.py:125 JsonPath值获取失败$.code
ERROR   2022-05-11 18:50:04,016  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 1
ERROR   2022-05-11 18:50:04,017  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-11 18:51:07,000  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-11 18:51:07,000  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 2
ERROR   2022-05-11 18:52:32,377  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-11 18:52:32,378  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 12
ERROR   2022-05-11 18:55:47,995  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-11 18:55:47,995  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-11 18:56:33,635  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-11 18:56:33,636  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-11 21:00:12,992  C:\work\Study\pytest-auto-api2\logs\error.log:assertControl.py:125 JsonPath值获取失败$.data.[0].[1].id
ERROR   2022-05-12 10:58:44,526  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 1
ERROR   2022-05-12 10:58:44,527  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-12 10:59:17,962  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-12 10:59:17,962  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-12 14:28:54,320  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-12 14:28:54,320  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-12 14:46:16,042  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-12 14:46:16,042  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-12 14:46:37,388  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 1
ERROR   2022-05-12 14:46:37,388  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-12 14:47:00,970  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-12 14:47:00,971  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-12 14:54:18,611  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-12 14:54:18,612  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 14
ERROR   2022-05-12 14:56:10,553  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-12 14:56:10,554  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 14
ERROR   2022-05-12 15:07:09,450  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-12 15:07:09,451  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
