ERROR   2022-04-26 11:48:38,701  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 11:48:38,706  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 2
ERROR   2022-04-26 15:21:26,894  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 15:21:26,895  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 2
ERROR   2022-04-26 16:34:12,155  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 16:34:12,156  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 0
ERROR   2022-04-26 16:46:33,019  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 6
ERROR   2022-04-26 16:46:33,019  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 0
ERROR   2022-04-26 16:48:46,253  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 5
ERROR   2022-04-26 16:48:46,255  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 0
ERROR   2022-04-26 16:52:27,292  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 16:52:27,293  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 2
ERROR   2022-04-26 16:54:24,827  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 16:54:24,828  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 2
ERROR   2022-04-26 17:06:40,095  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 17:06:40,096  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 2
ERROR   2022-04-26 17:07:38,190  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 17:07:38,191  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 2
ERROR   2022-04-26 17:19:49,536  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 17:19:49,537  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 0
ERROR   2022-04-26 17:20:12,459  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 17:20:12,461  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 0
ERROR   2022-04-26 17:24:47,145  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 17:24:47,145  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 0
ERROR   2022-04-26 17:39:03,954  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 6
ERROR   2022-04-26 17:39:03,956  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 0
ERROR   2022-04-26 17:45:35,521  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:130 异常用例数: 0
ERROR   2022-04-26 17:45:35,522  C:\Users\hzxy\Desktop\pytest-auto-api2\logs\error.log:conftest.py:131 失败用例数: 0
