WARNING 2022-05-23 13:46:36,085  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 0
WARNING 2022-05-23 13:48:17,786  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-23 13:52:21,859  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-23 13:58:00,074  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-23 18:00:24,527  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-23 18:29:47,695  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-23 20:51:42,964  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-24 10:12:30,587  C:\work\Study\pytest-auto-api2\logs\warning.log:logDecoratorl.py:52 
=================================================================================
该条用例跳过执行.
测试标题: 0510a6d1810dcd7c282ffce7d6979679
请求方式: a02439ec229d8be0e74b0c1602392310
请求头:   68b17859f66b062ee5e19484c63d3aa1
请求路径: fadd89a57f7dc1e419399f01ba55ae91
请求内容: 961859b6be07ee67a42859cf3c4f0e68
依赖测试用例: 暂无依赖用例数据
接口响应内容: {'data': {'desc': '', 'icon': '', 'id': 20021, 'link': 'https://gitee.com/yu_xiao_qi/pytest-auto-api2', 'name': '3152', 'order': 0, 'userId': 129462, 'visible': 1}, 'errorCode': 0, 'errorMsg': ''}
数据库断言数据: {'sql': None}
=================================================================================
WARNING 2022-05-24 10:12:30,780  C:\work\Study\pytest-auto-api2\logs\warning.log:logDecoratorl.py:52 
=================================================================================
该条用例跳过执行.
测试标题: 7d8a629963969fbb3eec8d6c86024c56
请求方式: a02439ec229d8be0e74b0c1602392310
请求头:   05bc3f9cab9bdb9f08987240ac9c7778
请求路径: fadd89a57f7dc1e419399f01ba55ae91
请求内容: ba63471189e77566fdb0a5d6d4a4db31
依赖测试用例: 暂无依赖用例数据
接口响应内容: {'data': {'desc': '', 'icon': '', 'id': 20022, 'link': 'https://gitee.com/yu_xiao_qi/pytest-auto-api2', 'name': '自动化编辑网址名称', 'order': 0, 'userId': 129462, 'visible': 1}, 'errorCode': 0, 'errorMsg': ''}
数据库断言数据: {'sql': None}
=================================================================================
WARNING 2022-05-24 16:18:31,674  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-24 16:28:51,665  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-25 11:37:11,550  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-25 17:28:08,519  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 0
WARNING 2022-05-25 17:28:59,022  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-25 17:29:15,945  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-25 17:32:50,697  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-26 11:36:09,287  C:\work\Study\pytest-auto-api2\logs\warning.log:teardownControl.py:89 程序中检查到您数据库开关为关闭状态，已为您跳过删除sql
WARNING 2022-05-26 11:36:26,768  C:\work\Study\pytest-auto-api2\logs\warning.log:teardownControl.py:89 程序中检查到您数据库开关为关闭状态，已为您跳过删除sql: select * from test_user;
WARNING 2022-05-26 13:49:52,622  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 10:53:06,233  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 10:55:23,858  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 0
WARNING 2022-05-27 10:55:40,832  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 0
WARNING 2022-05-27 10:56:31,543  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 10:59:15,093  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 16:53:27,350  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 16:55:41,888  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 16:57:23,740  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 16:58:01,840  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 16:59:51,930  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 17:00:45,798  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
WARNING 2022-05-27 17:01:28,964  C:\work\Study\pytest-auto-api2\logs\warning.log:conftest.py:133 跳过用例数: 1
